global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "sre-go-scratch"
    static_configs:
      - targets: ["sre-app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
